baseURL = 'https://duanjls.github.io/Duans-News-Website/'
languageCode = 'zh'
publishDir= 'docs'
title = 'acdNews'
theme = 'ananke'
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true